server:
    port: 8080
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: Girish
        url: jdbc:mysql://localhost:3306/springSecuritydb
        username: root
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        show-sql: true

   