server:
    port: 8082
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: Girish
        url: jdbc:mysql://localhost:3306/schooldb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
  
